### ISSUE TITLE
Running into Robot does not kill session 

### ISSUE THREAD

**Issue by XEOHASH** [3re/gravity-bugtracker#1]
Running into robot does not end session. Stayed at that same location for 30sec. This has been happening on several different levels! There was no Jump at the time. Screen Shot at Level 9...

Device: iOS

![img_2433](https://cloud.githubusercontent.com/assets/22961180/19564307/21061020-96b1-11e6-992b-8f5902739d1f.PNG)

**Comment by RdeWilde** [comment]
Haha cool public issues with screenshots
